In [ ]:
import pandas as pd
import numpy as np

In [ ]:
books = pd.read_csv('/content/drive/MyDrive/Projects /Data/all_kindle_review .csv')

In [ ]:
books.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [ ]:
books.rename(columns={'Unnamed: 0.1': 'ID'}, inplace=True)
display(books.head())

,ID,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [ ]:
books['reviewText'][1]

"Great short read.  I didn't want to put it down so I read it all in one sitting.  The sex scenes were great between the two males and one female character...a bit surprising - I never thought you could do that!  I learned something new and really enjoyed reading this book!  This is a great way to get all hot and bothered and take advantage of your significant other(s)!"

In [ ]:
books.shape

(12000, 11)

In [ ]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   ID              12000 non-null  int64 
 1   Unnamed: 0      12000 non-null  int64 
 2   asin            12000 non-null  object
 3   helpful         12000 non-null  object
 4   rating          12000 non-null  int64 
 5   reviewText      12000 non-null  object
 6   reviewTime      12000 non-null  object
 7   reviewerID      12000 non-null  object
 8   reviewerName    11962 non-null  object
 9   summary         11998 non-null  object
 10  unixReviewTime  12000 non-null  int64 
dtypes: int64(4), object(7)
memory usage: 1.0+ MB


In [ ]:
books.isnull().sum()

,0
ID,0
Unnamed: 0,0
asin,0
helpful,0
rating,0
reviewText,0
reviewTime,0
reviewerID,0
reviewerName,38
summary,2


In [ ]:
# ID, rating , reviewText , summary
books = books[['ID','rating','reviewText','summary']]

In [ ]:
books.isnull().sum()

,0
ID,0
rating,0
reviewText,0
summary,2


In [ ]:
books.dropna(inplace=True)

In [ ]:
books.isnull().sum()

,0
ID,0
rating,0
reviewText,0
summary,0


In [ ]:
books.duplicated().sum()

np.int64(0)

In [ ]:
books.head()

,ID,rating,reviewText,summary
0,0,3,"Jace Rankin may be short, but he's nothing to ...",Entertaining But Average
1,1,5,Great short read. I didn't want to put it dow...,Terrific menage scenes!
2,2,3,I'll start by saying this is the first of four...,Snapdragon Alley
3,3,3,Aggie is Angela Lansbury who carries pocketboo...,very light murder cozy
4,4,4,I did not expect this type of book to be in li...,Book


In [ ]:
books.rating.value_counts()

,count
rating,
5,2999
4,2999
3,2000
2,2000
1,2000


In [ ]:
books['rating']=books['rating'].replace([1,2],0)
books['rating']=books['rating'].replace([3,4,5],1)

In [ ]:
books.rating.value_counts()

,count
rating,
1,7998
0,4000


In [ ]:
books['tags'] = books['reviewText'] + books['summary']

In [ ]:
books.head()

,ID,rating,reviewText,summary,tags
0,0,1,"Jace Rankin may be short, but he's nothing to ...",Entertaining But Average,"Jace Rankin may be short, but he's nothing to ..."
1,1,1,Great short read. I didn't want to put it dow...,Terrific menage scenes!,Great short read. I didn't want to put it dow...
2,2,1,I'll start by saying this is the first of four...,Snapdragon Alley,I'll start by saying this is the first of four...
3,3,1,Aggie is Angela Lansbury who carries pocketboo...,very light murder cozy,Aggie is Angela Lansbury who carries pocketboo...
4,4,1,I did not expect this type of book to be in li...,Book,I did not expect this type of book to be in li...


In [ ]:
new_df = books[['ID','rating','tags']]

In [ ]:
new_df.head(2)

,ID,rating,tags
0,0,1,"Jace Rankin may be short, but he's nothing to ..."
1,1,1,Great short read. I didn't want to put it dow...


In [ ]:
sentiment_label = new_df['rating'].factorize()
sentiment_label

(array([0, 0, 0, ..., 0, 1, 0]), Index([1, 0], dtype='int64'))

In [ ]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_r

True

In [ ]:
new_df

,ID,rating,tags
0,0,1,"Jace Rankin may be short, but he's nothing to ..."
1,1,1,Great short read. I didn't want to put it dow...
2,2,1,I'll start by saying this is the first of four...
3,3,1,Aggie is Angela Lansbury who carries pocketboo...
4,4,1,I did not expect this type of book to be in li...
...,...,...,...
11995,11995,1,Valentine cupid is a vampire- Jena and Ian ano...
11996,11996,1,I have read all seven books in this series. Ap...
11997,11997,1,This book really just wasn't my cuppa. The si...
11998,11998,0,"tried to use it to charge my kindle, it didn't..."


In [ ]:
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords
def clean_text(raw_text):


    text = BeautifulSoup(raw_text, "html.parser").get_text()

    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.lower().split()

    stop_words = set(stopwords.words('english'))
    meaningful_words = [w for w in words if not w in stop_words]

    cleaned_text = " ".join(meaningful_words).strip()

    return cleaned_text

In [ ]:
new_df['tags'] = new_df['tags'].apply(clean_text)

/tmp/ipython-input-1957625099.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(clean_text)


In [ ]:
new_df.head()

,ID,rating,tags
0,0,1,jace rankin may short hes nothing mess man hau...
1,1,1,great short read didnt want put read one sitti...
2,2,1,ill start saying first four books wasnt expect...
3,3,1,aggie angela lansbury carries pocketbooks inst...
4,4,1,expect type book library pleased find price ri...


In [ ]:
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

In [ ]:
def lemmatize_words(text):
    return " ".join([wl.lemmatize(word) for word in text.split()])

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x : lemmatize_words(x))

/tmp/ipython-input-2176487967.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x : lemmatize_words(x))


In [ ]:
new_df.head()

,ID,rating,tags
0,0,1,jace rankin may short he nothing mess man haul...
1,1,1,great short read didnt want put read one sitti...
2,2,1,ill start saying first four book wasnt expecti...
3,3,1,aggie angela lansbury carry pocketbook instead...
4,4,1,expect type book library pleased find price ri...


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(new_df['tags'],new_df['rating'],test_size=.20)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 , stop_words = 'english')

In [ ]:
X_train_cv= cv.fit_transform(X_train).toarray()
X_test_cv=cv.transform(X_test).toarray()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [ ]:
X_train_tf= tf.fit_transform(X_train).toarray()
X_test_tf=tf.transform(X_test).toarray()

In [ ]:
X_test_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_tokenized = X_train.apply(lambda text: text.split())
X_test_tokenized = X_test.apply(lambda text: text.split())

In [ ]:
X_test_tokenized.iloc[0]

['disappointed',
 'book',
 'plot',
 'wandered',
 'coherence',
 'poor',
 'character',
 'development',
 'terribly',
 'interestingodd']

In [ ]:
cv.get_feature_names_out()

array(['aaron', 'abandoned', 'abby', ..., 'zone', 'zorn', 'zsadist'],
      dtype=object)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Train Logistic Regression model with CountVectorizer data
lg_model_cv = LogisticRegression().fit(X_train_cv, y_train)

# Make predictions on the test data
y_pred_cv = lg_model_cv.predict(X_test_cv)

# Evaluate the model
print("Confusion Matrix (CountVectorizer):")
print(confusion_matrix(y_test, y_pred_cv))
print("\nClassification Report (CountVectorizer):")
print(classification_report(y_test, y_pred_cv))
print("\nAccuracy Score (CountVectorizer):", accuracy_score(y_test, y_pred_cv))

Confusion Matrix (CountVectorizer):
[[ 620  249]
 [ 152 1379]]

Classification Report (CountVectorizer):
              precision    recall  f1-score   support

           0       0.80      0.71      0.76       869
           1       0.85      0.90      0.87      1531

    accuracy                           0.83      2400
   macro avg       0.83      0.81      0.81      2400
weighted avg       0.83      0.83      0.83      2400


Accuracy Score (CountVectorizer): 0.8329166666666666


In [ ]:
def predict_sentiment(text):
    cleaned_text = clean_text(text)
    # Use the fitted CountVectorizer to transform the text
    text_vector = cv.transform([cleaned_text])
    # Make sure the vector is in the correct format for the model
    text_vector = text_vector.reshape(1, -1)
    prediction = lg_model_cv.predict(text_vector)
    return prediction[0]

# Example usage:
test_sentence = "I like this book."
predicted_sentiment = predict_sentiment(test_sentence)

if predicted_sentiment == 1:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")

test_sentence_2 = "This book was terrible."
predicted_sentiment_2 = predict_sentiment(test_sentence_2)

if predicted_sentiment_2 == 1:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")

Predicted Sentiment: Negative
Predicted Sentiment: Negative


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Train Logistic Regression model with TfidfVectorizer data
lg_model_tf = LogisticRegression().fit(X_train_tf, y_train)

# Make predictions on the test data
y_pred_tf = lg_model_tf.predict(X_test_tf)

# Evaluate the model
print("Confusion Matrix (TfidfVectorizer):")
print(confusion_matrix(y_test, y_pred_tf))
print("\nClassification Report (TfidfVectorizer):")
print(classification_report(y_test, y_pred_tf))
print("\nAccuracy Score (TfidfVectorizer):", accuracy_score(y_test, y_pred_tf))

Confusion Matrix (TfidfVectorizer):
[[ 562  307]
 [  88 1443]]

Classification Report (TfidfVectorizer):
              precision    recall  f1-score   support

           0       0.86      0.65      0.74       869
           1       0.82      0.94      0.88      1531

    accuracy                           0.84      2400
   macro avg       0.84      0.79      0.81      2400
weighted avg       0.84      0.84      0.83      2400


Accuracy Score (TfidfVectorizer): 0.8354166666666667


In [ ]:
def predict_sentiment(text):
    cleaned_text = clean_text(text)
    # Use the fitted CountVectorizer to transform the text
    text_vector = tf.transform([cleaned_text])
    # Make sure the vector is in the correct format for the model
    text_vector = text_vector.reshape(1, -1)
    prediction = lg_model_tf.predict(text_vector)
    return prediction[0]

# Example usage:
test_sentence = "I like this book."
predicted_sentiment = predict_sentiment(test_sentence)

if predicted_sentiment == 1:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")

test_sentence_2 = "This book was terrible."
predicted_sentiment_2 = predict_sentiment(test_sentence_2)

if predicted_sentiment_2 == 1:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")

Predicted Sentiment: Negative
Predicted Sentiment: Negative
